version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres:/postgres
    environment:
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    command: npm run dev
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - postgres